// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Playlists");

function fn(i) {
  return React.createElement("li", {
              key: i[/* id */0]
            }, i[/* name */1]);
}

function make(playlists, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, React.createElement("h1", undefined, "Your Playlists"), React.createElement("ul", undefined, $$Array.of_list(List.map(fn, playlists))), React.createElement("button", {
                      className: "btn btn-primary"
                    }, "Add new..."));
    });
  return newrecord;
}

exports.component = component;
exports.fn = fn;
exports.make = make;
/* component Not a pure module */
