// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Playlists");

function fn(p) {
  return React.createElement("li", {
              key: p[/* id */0]
            }, p[/* name */1]);
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", undefined, React.createElement("h1", undefined, "Your Playlists"), React.createElement("ul", undefined, $$Array.of_list(List.map(fn, self[/* state */2][/* playlists */0]))), React.createElement("button", {
                      className: "btn btn-primary"
                    }, "Add new..."));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* playlists : :: */[
                /* record */[
                  /* id */"001",
                  /* name */"Number #1"
                ],
                /* :: */[
                  /* record */[
                    /* id */"002",
                    /* name */"Number #2"
                  ],
                  /* [] */0
                ]
              ]];
    });
  newrecord[/* reducer */12] = (function (_, _$1) {
      return /* NoUpdate */0;
    });
  return newrecord;
}

exports.component = component;
exports.fn = fn;
exports.make = make;
/* component Not a pure module */
